### ISSUE TITLE
Error compiling with compass

### ISSUE THREAD

**Issue by ninapavlich** [dahlia/libsass-python#51] opened 2015-03-15 21:09 UTC
I'm getting this error when trying to include compass:
"tmp/compass/compass/_support.scss:152: named arguments must precede variable-length argument"

Line 152 of _support.scss contains:
@include for-legacy-browser($browser, $range..., $threshold: $threshold, $ranges: $browsers) {

My code contains:
source = '@import "compass"; .... some styles here ....'
src_directories = ['tmp/somestyles', '/tmp/compass/']
compiled = sass.compile(string=source,include_paths=src_directories)

I'm using the latest version of Compass from Jan 15 (compass-1.0.3) and version 0.7.0 of libsass

Thanks!

**Comment by dahlia** [comment] 2015-03-17 06:12
Could it be reproduced with the official [sassc][] as well?

[sassc]: https://github.com/sass/sassc

**Comment by lallen** [comment] 2015-07-22 10:40
https://github.com/sass/libsass/issues/1259
Confirmed in libsass.

**Comment by asottile** [comment] 2015-12-04 16:12
Since the bug is in the upstream libsass, I'm going to close this and let them track it there :)

**Closed by asottile** 2015-12-04 16:12 UTC
