### ISSUE TITLE
Fail with materialize scss.  Using libsass-python(0.13.2)

### ISSUE THREAD

**Issue by diansheng** [dahlia/libsass-python#220] opened 2017-09-29 10:55 UTC
This issue is related to [an issue](https://github.com/sass/libsass/issues/2427) of the underlying c library [sass/libsass](https://github.com/sass/libsass).

------
**Cause**  
And libsass-python(0.13.2) is using sass/libsass(3.4.5)
If use materialise scss with [sass/libsass](https://github.com/sass/libsass) version 3.4.5, you may come across this following error.
```
Invalid CSS after "...ing-left: 2rem;": expected "}", was "&:focus, &[type=tex"
        on line 166 of static/materialize/sass/components/_navbar.scss
>>       padding-left: 2rem;
```

------
**Possible temporary solution:**
Downgrade lib sass-python to version (0.13.0) which does not use sass/libsass(3.4.5)

**Comment by asottile** [comment] 2017-09-29 14:46
This is a duplicate of #210.  We'll get a release out as soon as upstream releases it!

Thanks again for the issue :)

**Closed by asottile** 2017-09-29 14:46 UTC

**Comment by asottile** [comment] 2017-10-12 16:45
I believe 0.13.3 has a fix for this!
